-- Execute no SQL editor de um projeto Supabase novo. Requer pgcrypto.
create extension if not exists pgcrypto;
create table public.workspaces(id uuid primary key default gen_random_uuid(),name text not null check(length(name) between 2 and 120),created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.memberships(workspace_id uuid not null references public.workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in ('owner','admin','editor','viewer')),created_at timestamptz not null default now(),primary key(workspace_id,user_id));
create table public.entries(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,kind text not null check(kind in ('decisao','conduta','regra','reuniao','treinamento','feedback','conhecimento')),title text not null check(length(title) between 1 and 180),body text not null check(length(body) between 1 and 30000),status text not null default 'rascunho' check(status in ('rascunho','vigente','arquivado')),occurred_at timestamptz not null default now(),source_url text,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.tasks(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,title text not null check(length(title) between 1 and 500),done boolean not null default false,due_at timestamptz,created_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table public.attendance(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.workspaces(id) on delete cascade,entry_id uuid not null references public.entries(id) on delete cascade,participant_name text not null check(length(participant_name) between 1 and 180),present boolean not null default true,recorded_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(entry_id,participant_name));
create table public.audit_events(id bigint generated always as identity primary key,workspace_id uuid not null,entity text not null,entity_id uuid not null,operation text not null,actor uuid,changed_at timestamptz not null default now(),payload jsonb not null);
create index on public.entries(workspace_id,occurred_at desc);create index on public.tasks(workspace_id,done);create index on public.attendance(workspace_id,entry_id);create index on public.audit_events(workspace_id,changed_at desc);
alter table public.workspaces enable row level security;alter table public.memberships enable row level security;alter table public.entries enable row level security;alter table public.tasks enable row level security;alter table public.attendance enable row level security;alter table public.audit_events enable row level security;
create function public.has_membership(w uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.memberships where workspace_id=w and user_id=(select auth.uid()))$$;
create function public.can_edit(w uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.memberships where workspace_id=w and user_id=(select auth.uid()) and role in ('owner','admin','editor'))$$;
create policy workspace_read on public.workspaces for select to authenticated using(public.has_membership(id));
create policy membership_read on public.memberships for select to authenticated using(public.has_membership(workspace_id));
create policy entry_read on public.entries for select to authenticated using(public.has_membership(workspace_id));
create policy entry_insert on public.entries for insert to authenticated with check(public.can_edit(workspace_id) and created_by=(select auth.uid()));
create policy tasks_read on public.tasks for select to authenticated using(public.has_membership(workspace_id));
create policy tasks_insert on public.tasks for insert to authenticated with check(public.can_edit(workspace_id) and created_by=(select auth.uid()));
create policy tasks_update on public.tasks for update to authenticated using(public.can_edit(workspace_id)) with check(public.can_edit(workspace_id));
create policy attendance_read on public.attendance for select to authenticated using(public.has_membership(workspace_id));
create policy attendance_insert on public.attendance for insert to authenticated with check(public.can_edit(workspace_id) and recorded_by=(select auth.uid()) and exists(select 1 from public.entries e where e.id=entry_id and e.workspace_id=attendance.workspace_id and e.kind in ('treinamento','reuniao')));
create policy audit_read on public.audit_events for select to authenticated using(public.has_membership(workspace_id));
create function public.create_workspace(workspace_name text) returns uuid language plpgsql security definer set search_path='' as $$declare new_id uuid;begin if (select auth.uid()) is null then raise exception 'not authenticated';end if;if length(trim(workspace_name)) not between 2 and 120 then raise exception 'invalid name';end if;insert into public.workspaces(name,created_by) values(trim(workspace_name),(select auth.uid())) returning id into new_id;insert into public.memberships(workspace_id,user_id,role) values(new_id,(select auth.uid()),'owner');return new_id;end$$;
revoke all on function public.create_workspace(text) from public;grant execute on function public.create_workspace(text) to authenticated;
create function public.audit_change() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.audit_events(workspace_id,entity,entity_id,operation,actor,payload) values(coalesce(new.workspace_id,old.workspace_id),tg_table_name,coalesce(new.id,old.id),tg_op,(select auth.uid()),case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end);return coalesce(new,old);end$$;
create trigger entry_audit after insert or update or delete on public.entries for each row execute function public.audit_change();
create trigger task_audit after insert or update or delete on public.tasks for each row execute function public.audit_change();
create trigger attendance_audit after insert or update or delete on public.attendance for each row execute function public.audit_change();
-- Proteção contra alterações por clientes nos logs: apenas SELECT via RLS. Papéis service_role e owners do banco podem manter dados.
