'use client';
import {useEffect,useState,useMemo} from 'react';
import {supabase,configured} from '../lib/supabase';
import {KINDS,type Kind,type Entry} from '../lib/types';
import {BrainCircuit,LayoutDashboard,BookOpen,CalendarDays,GraduationCap,Scale,Users,ShieldCheck,Search,Plus,LogOut,Menu,X,ArrowRight,Sparkles,CheckCircle2,ClipboardList,History,Send} from 'lucide-react';
import type {User} from '@supabase/supabase-js';
type Workspace={id:string;name:string;role:string};
const menus=[{id:'inicio',label:'Visão geral',icon:LayoutDashboard},{id:'registros',label:'Base de conhecimento',icon:BookOpen},{id:'reunioes',label:'Reuniões',icon:CalendarDays},{id:'treinamentos',label:'Treinamentos',icon:GraduationCap},{id:'decisoes',label:'Decisões e regras',icon:Scale},{id:'tarefas',label:'Ações',icon:ClipboardList},{id:'atlas',label:'ATLAS AI',icon:BrainCircuit}];
const labels:Record<Kind,string>={decisao:'Decisão',conduta:'Conduta',regra:'Regra',reuniao:'Reunião',treinamento:'Treinamento',feedback:'Feedback',conhecimento:'Conhecimento'};
export default function Home(){
const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState<'login'|'signup'>('login');
const [workspaces,setWorkspaces]=useState<Workspace[]>([]),[wid,setWid]=useState(''),[newWorkspace,setNewWorkspace]=useState(''),[entries,setEntries]=useState<Entry[]>([]),[section,setSection]=useState('inicio'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(false),[mobile,setMobile]=useState(false);
const [kind,setKind]=useState<Kind>('decisao'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[source,setSource]=useState(''),[occurred,setOccurred]=useState(new Date().toISOString().slice(0,10)),[status,setStatus]=useState<'rascunho'|'vigente'>('rascunho');
const [tasks,setTasks]=useState<{id:string;title:string;done:boolean;due_at:string|null}[]>([]),[taskTitle,setTaskTitle]=useState(''),[attEntry,setAttEntry]=useState(''),[attName,setAttName]=useState(''),[attendance,setAttendance]=useState<{id:string;participant_name:string;present:boolean;entry_id:string}[]>([]);
const [ask,setAsk]=useState(''),[answer,setAnswer]=useState(''),[asking,setAsking]=useState(false);
useEffect(()=>{if(!supabase){setReady(true);return;}supabase.auth.getUser().then(({data})=>{setUser(data.user);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!user||!supabase){setWorkspaces([]);return;}supabase.from('memberships').select('workspace_id,role,workspaces(name)').then(({data,error})=>{if(error)setError(error.message);const rows=(data||[]) as unknown as {workspace_id:string;role:string;workspaces:{name:string}|null}[];setWorkspaces(rows.map(r=>({id:r.workspace_id,name:r.workspaces?.name||'Workspace',role:r.role})));setWid(v=>rows.some(r=>r.workspace_id===v)?v:rows[0]?.workspace_id||'')})},[user]);
async function refresh(id:string){if(!supabase||!id)return;const [e,t,a]=await Promise.all([supabase.from('entries').select('*').eq('workspace_id',id).order('occurred_at',{ascending:false}).limit(500),supabase.from('tasks').select('id,title,done,due_at').eq('workspace_id',id).order('created_at',{ascending:false}),supabase.from('attendance').select('id,participant_name,present,entry_id').eq('workspace_id',id)]);if(e.error)setError(e.error.message);setEntries((e.data||[]) as Entry[]);setTasks(t.data||[]);setAttendance(a.data||[])}
useEffect(()=>{void refresh(wid)},[wid]);
const filtered=useMemo(()=>entries.filter(e=>(section==='reunioes'?e.kind==='reuniao':section==='treinamentos'?e.kind==='treinamento':section==='decisoes'?['decisao','regra','conduta'].includes(e.kind):true)&&[e.title,e.body,labels[e.kind]].join(' ').toLowerCase().includes(query.toLowerCase())),[entries,section,query]);
const canEdit=workspaces.find(w=>w.id===wid)?.role!=='viewer';
async function authenticate(){if(!supabase)return;setBusy(true);setError('');const result=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)setError(result.error.message);else if(authMode==='signup')setError('Cadastro recebido. Confirme o e-mail antes de entrar, se exigido.');setBusy(false)}
async function createWorkspace(){if(!supabase||!newWorkspace.trim())return;setBusy(true);const {data,error}=await supabase.rpc('create_workspace',{workspace_name:newWorkspace.trim()});if(error)setError(error.message);else{setWorkspaces(w=>[...w,{id:data,name:newWorkspace,role:'owner'}]);setWid(data);setNewWorkspace('')}setBusy(false)}
async function saveEntry(){if(!supabase||!wid||!title.trim()||!body.trim())return;setBusy(true);const {error}=await supabase.from('entries').insert({workspace_id:wid,kind,title:title.trim(),body:body.trim(),status,occurred_at:new Date(occurred+'T12:00:00').toISOString(),source_url:source.trim()||null,created_by:user!.id});if(error)setError(error.message);else{setModal(false);setTitle('');setBody('');setSource('');await refresh(wid)}setBusy(false)}
async function addTask(){if(!supabase||!taskTitle.trim())return;const {error}=await supabase.from('tasks').insert({workspace_id:wid,title:taskTitle.trim(),created_by:user!.id});if(error)setError(error.message);else{setTaskTitle('');await refresh(wid)}}
async function toggleTask(t:{id:string;done:boolean}){if(!supabase)return;const {error}=await supabase.from('tasks').update({done:!t.done}).eq('id',t.id);if(error)setError(error.message);else await refresh(wid)}
async function addAttendance(){if(!supabase||!attEntry||!attName.trim())return;const {error}=await supabase.from('attendance').insert({workspace_id:wid,entry_id:attEntry,participant_name:attName.trim(),present:true,recorded_by:user!.id});if(error)setError(error.message);else{setAttName('');await refresh(wid)}}
async function askAtlas(){if(!supabase||!ask.trim())return;setAsking(true);setAnswer('');const session=await supabase.auth.getSession();try{const r=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.data.session?.access_token},body:JSON.stringify({question:ask,workspaceId:wid})});const data=await r.json();setAnswer(data.answer||data.error||'Não foi possível responder.')}catch{setAnswer('Falha de conexão.')}setAsking(false)}
if(!ready)return <main className="loading">Carregando ATLAS...</main>;
if(!configured)return <main className="setup"><div className="orb">✦</div><h1>ATLAS</h1><p>Conecte seu ambiente seguro para começar.</p><code>Configure NEXT_PUBLIC_SUPABASE_URL e NEXT_PUBLIC_SUPABASE_ANON_KEY</code><p>Consulte o README e execute supabase/schema.sql.</p></main>;
if(!user)return <main className="auth-wrap"><div className="auth-card"><div className="brand"><span className="mark"><BrainCircuit size={26}/></span><span>ATLAS <small>WORKSPACE</small></span></div><h1>O conhecimento da sua equipe, conectado.</h1><p>Seu segundo cérebro organizacional começa aqui.</p><form onSubmit={e=>{e.preventDefault();void authenticate()}}><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} autoComplete={authMode==='login'?'current-password':'new-password'}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{authMode==='login'?'Entrar':'Criar conta'} <ArrowRight size={17}/></button></form><button className="link" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Criar uma conta':'Já tenho conta'}</button></div></main>;
return <div className="shell"><aside className={mobile?'sidebar show':'sidebar'}><div className="brand"><span className="mark"><BrainCircuit size={24}/></span><span>ATLAS <small>INTELLIGENCE HUB</small></span><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div><div className="space-select"><span>ORGANIZAÇÃO</span><select value={wid} onChange={e=>setWid(e.target.value)}>{workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div className="nav-label">WORKSPACE</div><nav>{menus.map(m=><button className={section===m.id?'active':''} key={m.id} onClick={()=>{setSection(m.id);setMobile(false);setQuery('')}}><m.icon size={19}/>{m.label}</button>)}</nav><div className="side-bottom"><div className="secure"><ShieldCheck size={17}/> Dados por permissão</div><button onClick={()=>void supabase?.auth.signOut()}><LogOut size={18}/> Sair da conta</button></div></aside>{mobile&&<div className="veil" onClick={()=>setMobile(false)}/>}
<main className="main"><header className="topbar"><button className="mobile-toggle" onClick={()=>setMobile(true)}><Menu/></button><div className="breadcrumbs">Workspace <span>/</span> {menus.find(m=>m.id===section)?.label}</div><div className="top-right"><span className="date">{new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long',year:'numeric'}).format(new Date())}</span><div className="avatar">{(user.email||'A')[0].toUpperCase()}</div></div></header>
<div className="content">{error&&<div className="errorbar">{error}<button onClick={()=>setError('')}><X size={16}/></button></div>}{!wid?<section className="empty"><h2>Crie seu workspace</h2><p>Um espaço privado para sua organização e seus registros.</p><div className="inline"><input placeholder="Nome da organização" value={newWorkspace} onChange={e=>setNewWorkspace(e.target.value)}/><button className="primary" onClick={createWorkspace} disabled={busy}>Criar workspace</button></div></section>:<>
{section==='inicio'&&<><div className="eyebrow">CENTRAL DE INTELIGÊNCIA</div><div className="welcome"><div><h1>Seu conhecimento, em movimento<span className="purple">.</span></h1><p>Uma visão clara do que sua organização aprendeu, decidiu e precisa executar.</p></div><button className="primary" disabled={!canEdit} onClick={()=>setModal(true)}><Plus size={18}/> Novo registro</button></div><div className="stats"><div className="stat"><BookOpen/><span>Registros</span><strong>{entries.length}</strong><small>Base institucional</small></div><div className="stat"><Scale/><span>Decisões e regras</span><strong>{entries.filter(e=>['decisao','regra','conduta'].includes(e.kind)).length}</strong><small>Histórico documentado</small></div><div className="stat"><GraduationCap/><span>Treinamentos</span><strong>{entries.filter(e=>e.kind==='treinamento').length}</strong><small>Eventos registrados</small></div><div className="stat"><CheckCircle2/><span>Ações abertas</span><strong>{tasks.filter(t=>!t.done).length}</strong><small>Aguardando conclusão</small></div></div><div className="two-col"><section className="panel"><div className="panel-head"><h3>Memória recente</h3><button onClick={()=>setSection('registros')}>Ver todos <ArrowRight size={14}/></button></div>{entries.slice(0,6).map(e=><div className="entry" key={e.id}><span className="entry-icon"><History size={18}/></span><div><strong>{e.title}</strong><small>{labels[e.kind]} · {new Date(e.occurred_at).toLocaleDateString('pt-BR')} · {e.status}</small></div></div>)}{entries.length===0&&<p className="muted pad">Nenhum registro ainda. Comece capturando uma decisão ou reunião.</p>}</section><section className="ai-panel"><div className="spark"><Sparkles/></div><h3>Conheça o ATLAS AI</h3><p>Transforme arquivos e registros em respostas contextualizadas. Cada resposta aponta para suas fontes.</p><button onClick={()=>setSection('atlas')}>Consultar inteligência <ArrowRight size={17}/></button></section></div></>}
{['registros','reunioes','treinamentos','decisoes'].includes(section)&&<><div className="page-heading"><div><div className="eyebrow">MEMÓRIA INSTITUCIONAL</div><h1>{menus.find(m=>m.id===section)?.label}</h1><p>Informações organizadas, recuperáveis e com autoria rastreável.</p></div><button className="primary" disabled={!canEdit} onClick={()=>{setKind(section==='reunioes'?'reuniao':section==='treinamentos'?'treinamento':section==='decisoes'?'decisao':'conhecimento');setModal(true)}}><Plus size={18}/> Novo registro</button></div><div className="search"><Search size={20}/><input placeholder="Buscar por título, conteúdo ou categoria..." value={query} onChange={e=>setQuery(e.target.value)}/></div><section className="panel list-panel">{filtered.map(e=><article className="record" key={e.id}><div className="record-meta"><span className="tag">{labels[e.kind]}</span><span>{new Date(e.occurred_at).toLocaleDateString('pt-BR')}</span><span className="status">{e.status}</span></div><h3>{e.title}</h3><p>{e.body}</p>{e.source_url&&<a href={e.source_url} target="_blank" rel="noopener noreferrer">Abrir fonte <ArrowRight size={14}/></a>}{['reuniao','treinamento'].includes(e.kind)&&<div className="attendance"><Users size={15}/> {attendance.filter(a=>a.entry_id===e.id&&a.present).length} presenças registradas</div>}</article>)}{filtered.length===0&&<p className="muted pad">Nenhum resultado encontrado.</p>}</section>{section==='treinamentos'&&canEdit&&<section className="panel attendance-form"><h3>Registrar presença</h3><div className="inline"><select value={attEntry} onChange={e=>setAttEntry(e.target.value)}><option value="">Selecione o treinamento</option>{entries.filter(e=>e.kind==='treinamento').map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select><input placeholder="Nome do participante" value={attName} onChange={e=>setAttName(e.target.value)}/><button className="primary" onClick={addAttendance}>Confirmar</button></div><p className="muted">Presenças são registradas individualmente. Use apenas dados autorizados.</p></section>}</>}
{section==='tarefas'&&<><div className="page-heading"><div><div className="eyebrow">EXECUÇÃO</div><h1>Ações e compromissos</h1><p>Transforme decisões em trabalho verificável.</p></div></div>{canEdit&&<div className="inline task-entry"><input placeholder="Descreva uma nova ação" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/><button className="primary" onClick={addTask}><Plus size={17}/> Adicionar</button></div>}<section className="panel list-panel">{tasks.map(t=><div className="task" key={t.id}><button disabled={!canEdit} onClick={()=>toggleTask(t)}><CheckCircle2 size={22} color={t.done?'#19a88b':'#94a3b8'}/></button><span style={{textDecoration:t.done?'line-through':'none',opacity:t.done?.55:1}}>{t.title}</span><small>{t.done?'Concluída':'Pendente'}</small></div>)}{tasks.length===0&&<p className="muted pad">Nenhuma ação cadastrada.</p>}</section></>}
{section==='atlas'&&<><div className="eyebrow">INTELIGÊNCIA CONTEXTUAL</div><div className="ai-hero"><div className="spark"><Sparkles size={26}/></div><h1>Pergunte ao ATLAS.</h1><p>Respostas com base nos registros aos quais você tem acesso. A IA não altera dados nem inventa regras.</p></div><div className="ask-box"><textarea value={ask} onChange={e=>setAsk(e.target.value)} placeholder="Ex.: Quais foram as principais decisões nas últimas reuniões?" rows={3}/><button className="primary" disabled={asking||!ask.trim()} onClick={askAtlas}><Send size={17}/>{asking?'Analisando...':'Perguntar'}</button></div>{answer&&<section className="panel answer"><div className="answer-head"><Sparkles size={18}/> Resposta ATLAS</div><div className="answer-body">{answer}</div></section>}<p className="muted hint">O ATLAS usa apenas registros permitidos neste workspace. Verifique fontes antes de decisões sensíveis.</p></>}
</>}</div></main>{modal&&<div className="modal-backdrop"><div className="modal"><header><div><div className="eyebrow">NOVO CONHECIMENTO</div><h2>Adicionar registro</h2></div><button onClick={()=>setModal(false)}><X/></button></header><form onSubmit={e=>{e.preventDefault();void saveEntry()}}><label>Categoria<select value={kind} onChange={e=>setKind(e.target.value as Kind)}>{KINDS.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={180}/></label><label>Conteúdo / decisões / contexto<textarea value={body} onChange={e=>setBody(e.target.value)} rows={6} required maxLength={30000}/></label><div className="form-row"><label>Data<input type="date" value={occurred} onChange={e=>setOccurred(e.target.value)} required/></label><label>Situação<select value={status} onChange={e=>setStatus(e.target.value as 'rascunho'|'vigente')}><option value="rascunho">Rascunho</option><option value="vigente">Vigente</option></select></label></div><label>URL da fonte (opcional)<input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://..."/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>Cancelar</button><button className="primary" disabled={busy}>Salvar registro</button></div></form></div></div>}</div>
}