'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
type Attachment={id:string;original_name:string;storage_path:string;sha256:string;version:number;created_at:string;source_url:string|null;entry_id:string|null};
const allowed=['application/pdf','text/plain','text/csv','application/json','image/png','image/jpeg'];
export default function DocumentsPanel({workspaceId,userId,canEdit,entries}:{workspaceId:string;userId:string;canEdit:boolean;entries:{id:string;title:string}[]}){
 const [items,setItems]=useState<Attachment[]>([]),[file,setFile]=useState<File|null>(null),[hash,setHash]=useState(''),[preview,setPreview]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function refresh(){if(!supabase||!workspaceId)return;const {data,error}=await supabase.from('record_attachments').select('id,original_name,storage_path,sha256,version,created_at,source_url,entry_id').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(100);if(error)setNotice(error.message);else setItems(data||[])}
 useEffect(()=>{void refresh()},[workspaceId]);
 async function pick(f:File|undefined){setFile(null);setHash('');setPreview('');setConsent(false);setNotice('');if(!f)return;if(!allowed.includes(f.type)||f.size<1||f.size>5242880){setNotice('Somente PDF, TXT, CSV, JSON, PNG ou JPEG de até 5 MB.');return}const bytes=await f.arrayBuffer();const raw=await crypto.subtle.digest('SHA-256',bytes);setHash(Array.from(new Uint8Array(raw),x=>x.toString(16).padStart(2,'0')).join(''));setPreview(['text/plain','text/csv','application/json'].includes(f.type)?new TextDecoder().decode(bytes.slice(0,8000)):'Arquivo binário: confira o nome antes de confirmar.');setFile(f)}
 async function submit(){if(!supabase||!file||!consent||!hash)return;setBusy(true);setNotice('');if(items.some(x=>x.sha256===hash)){setNotice('Já existe um arquivo idêntico neste workspace.');setBusy(false);return}const path=workspaceId+'/'+userId+'/'+crypto.randomUUID()+'/'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const uploaded=await supabase.storage.from('atlas-private').upload(path,file,{upsert:false,contentType:file.type});if(uploaded.error){setNotice(uploaded.error.message);setBusy(false);return}const inserted=await supabase.from('record_attachments').insert({workspace_id:workspaceId,storage_path:path,original_name:file.name,content_type:file.type,byte_size:file.size,sha256:hash,uploaded_by:userId,source_url:origin.trim()||null,entry_id:linkedEntry||null});if(inserted.error){const cleaned=await supabase.storage.from('atlas-private').remove([path]);setNotice(cleaned.error?'Metadados falharam e o arquivo precisa de revisão: '+inserted.error.message:'Importação revertida: '+inserted.error.message)}else{setNotice('Documento importado.');setFile(null);setConsent(false);setOrigin('');setLinkedEntry('');await refresh()}setBusy(false)}
 async function view(x:Attachment){if(!supabase)return;const {data,error}=await supabase.storage.from('atlas-private').createSignedUrl(x.storage_path,60);if(error)setNotice(error.message);else if(data)window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 return <div><div className="page-heading"><div><div className="eyebrow">MEMÓRIA</div><h1>Documentos privados</h1><p>Arquivos vinculados à organização, não publicados no GitHub.</p></div></div>
 {canEdit&&<section className="panel attendance-form"><h3>Importar documento</h3><input type="file" aria-label="Selecionar documento" accept=".pdf,.txt,.csv,.json,.png,.jpg,.jpeg" onChange={e=>void pick(e.target.files?.[0])}/>{file&&<><p>{file.name} · {Math.ceil(file.size/1024)} KB</p><pre style={{whiteSpace:'pre-wrap',maxHeight:200,overflow:'auto'}}>{preview}</pre><p className="muted">SHA-256: {hash}</p><label>Registro relacionado<select aria-label="Registro relacionado" value={linkedEntry} onChange={e=>setLinkedEntry(e.target.value)}><option value="">Sem vínculo</option>{entries.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Origem do arquivo<input type="url" placeholder="https://..." value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Confirmo que tenho autorização para armazenar este arquivo.</label><button className="primary" disabled={!consent||busy} onClick={()=>void submit()}>Confirmar importação</button></>}</section>}
 <section className="panel attendance-form"><h3>Arquivos recentes</h3>{items.map(x=><div className="task" key={x.id}><span>{x.original_name} · versão {x.version}</span><button className="secondary" onClick={()=>void view(x)}>Abrir temporariamente</button>{x.source_url&&<a href={x.source_url} target="_blank" rel="noopener noreferrer">Fonte original</a>}</div>)}{items.length===0&&<p className="muted">Nenhum documento encontrado.</p>}</section>{notice&&<p role="status">{notice}</p>}</div>
}