'use client';
import {useMemo,useState} from 'react';
import type {Entry,Kind} from '../lib/types';
import {Search,FileText,ShieldCheck,Clock3,Download} from 'lucide-react';
const names:Record<Kind,string>={decisao:'Decisão',conduta:'Conduta',regra:'Regra',reuniao:'Reunião',treinamento:'Treinamento',feedback:'Feedback',conhecimento:'Conhecimento'};
export default function GovernancePanel({entries,role,onApprove}:{entries:Entry[];role:string;onApprove:(id:string)=>Promise<void>}){
 const [text,setText]=useState(''),[status,setStatus]=useState('todos'),[kind,setKind]=useState('todos'),[busy,setBusy]=useState('');
 const selected=useMemo(()=>entries.filter(e=>(status==='todos'||e.status===status)&&(kind==='todos'||e.kind===kind)&&(!text.trim()||(e.title+' '+e.body).toLocaleLowerCase('pt-BR').includes(text.trim().toLocaleLowerCase('pt-BR')))),[entries,text,status,kind]);
 const pending=entries.filter(e=>e.status==='rascunho').length;
 const current=entries.filter(e=>e.status==='vigente').length;
 async function approve(id:string){setBusy(id);try{await onApprove(id)}finally{setBusy('')}}
 function exportCsv(){const escape=(s:string)=>'"'+s.replaceAll('"','""')+'"';const rows=[['Tipo','Título','Status','Data','Origem'],...selected.map(e=>[names[e.kind],e.title,e.status,new Date(e.occurred_at).toLocaleDateString('pt-BR'),e.source_url||''])];const csv='\uFEFF'+rows.map(r=>r.map(escape).join(';')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='atlas-registros.csv';a.click();URL.revokeObjectURL(url)}
 return <div><div className="eyebrow">CONSELHO ATLAS</div><div className="page-heading"><div><h1>Governança e pesquisa</h1><p>Encontre evidências, acompanhe revisões e saiba o que está oficialmente vigente.</p></div></div>
 <div className="stats governance-stats"><div className="stat"><FileText/><span>Registros acessíveis</span><strong>{entries.length}</strong><small>Últimos 500 registros carregados</small></div><div className="stat"><ShieldCheck/><span>Vigentes</span><strong>{current}</strong><small>Conhecimento aprovado</small></div><div className="stat"><Clock3/><span>Rascunhos</span><strong>{pending}</strong><small>Aguardando revisão</small></div></div>
 <div className="governance-controls"><div className="search"><Search size={18}/><input aria-label="Pesquisar registros" placeholder="Pesquisar evidências e títulos..." value={text} onChange={e=>setText(e.target.value)}/></div><select aria-label="Filtrar situação" value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todas as situações</option><option value="vigente">Vigentes</option><option value="rascunho">Rascunhos</option><option value="arquivado">Arquivados</option></select><select aria-label="Filtrar categoria" value={kind} onChange={e=>setKind(e.target.value)}><option value="todos">Todas as categorias</option>{Object.entries(names).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><button className="secondary" onClick={exportCsv}><Download size={16}/> Exportar CSV</button></div>
 <section className="panel list-panel">{selected.map(e=><article key={e.id} className="record"><div className="record-meta"><span className="tag">{names[e.kind]}</span><span>{new Date(e.occurred_at).toLocaleDateString('pt-BR')}</span><span className="status">{e.status}</span></div><h3>{e.title}</h3><p>{e.body}</p>{e.source_url&&<a rel="noopener noreferrer" target="_blank" href={e.source_url}>Consultar fonte</a>}{e.status==='rascunho'&&['owner','admin'].includes(role)&&<div style={{marginTop:12}}><button className="primary" disabled={busy===e.id} onClick={()=>approve(e.id)}>Aprovar publicação</button></div>}</article>)}{selected.length===0&&<p className="muted pad">Nenhum registro corresponde aos filtros.</p>}</section><p className="muted hint">Os resultados respeitam as permissões RLS do Supabase. A exportação inclui apenas os itens filtrados e carregados nesta sessão.</p></div>
}