'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
type Notice={id:string;kind:'approval'|'overdue';entity_id:string;title:string;read_at:string|null;created_at:string};
export default function NotificationsPanel({workspaceId,onNavigate}:{workspaceId:string;onNavigate:(section:string)=>void}){
 const [items,setItems]=useState<Notice[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){if(!supabase||!workspaceId)return;setBusy(true);setError('');const refresh=await supabase.rpc('refresh_my_notifications',{target_workspace:workspaceId});if(refresh.error){setError(refresh.error.message);setBusy(false);return;}const {data,error}=await supabase.from('notifications').select('id,kind,entity_id,title,read_at,created_at').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(100);setItems((data||[]) as Notice[]);if(error)setError(error.message);setBusy(false)}
 useEffect(()=>{void load()},[workspaceId]);
 async function mark(item:Notice){if(!supabase)return;const {error}=await supabase.from('notifications').update({read_at:item.read_at?null:new Date().toISOString()}).eq('id',item.id);if(error)setError(error.message);else setItems(v=>v.map(n=>n.id===item.id?{...n,read_at:item.read_at?null:new Date().toISOString()}:n))}
 const unread=items.filter(n=>!n.read_at).length;
 return <div><div className="page-heading"><div><div className="eyebrow">ACOMPANHAMENTO PESSOAL</div><h1>Notificações</h1><p>{unread} aviso(s) não lido(s). Estado de leitura salvo em sua conta.</p></div><button className="secondary" onClick={load} disabled={busy}>{busy?'Atualizando...':'Atualizar'}</button></div><section className="panel list-panel" aria-busy={busy}>{error&&<p className="error pad" role="alert">{error}</p>}{!busy&&items.length===0&&!error&&<p className="muted pad">Nenhum aviso para este workspace.</p>}{items.map(n=><article className="audit-event" key={n.id}><div className="audit-event-title"><strong>{n.kind==='approval'?'Aprovação pendente':'Ação atrasada'}{!n.read_at?' · Novo':''}</strong><time>{new Date(n.created_at).toLocaleString('pt-BR')}</time></div><p>{n.title}</p><button className="secondary" onClick={()=>onNavigate(n.kind==='approval'?'governanca':'tarefas')}>Abrir área</button><button className="secondary" onClick={()=>mark(n)}>{n.read_at?'Marcar como não lido':'Marcar como lido'}</button></article>)}</section><p className="muted hint">Os avisos são atualizados ao abrir ou atualizar esta área. Não são notificações push ou por e-mail.</p></div>
}