'use client';
import {useMemo,useState} from 'react';
import type {Entry} from '../lib/types';
type Task={id:string;title:string;done:boolean;due_at:string|null};
export default function PendingCenter({entries,tasks,role,onNavigate,onRefresh}:{entries:Entry[];tasks:Task[];role:string;onNavigate:(section:string)=>void;onRefresh:()=>Promise<void>}){
 const [tab,setTab]=useState<'all'|'approval'|'overdue'>('all');const [refreshing,setRefreshing]=useState(false);
 const allowed=['owner','admin'].includes(role);
 const waiting=useMemo(()=>allowed?entries.filter(e=>e.status==='rascunho'):[],[allowed,entries]);
 const overdue=useMemo(()=>tasks.filter(t=>!t.done&&Boolean(t.due_at)&&new Date(t.due_at!).getTime()<Date.now()),[tasks]);
 const soon=useMemo(()=>tasks.filter(t=>!t.done&&Boolean(t.due_at)&&new Date(t.due_at!).getTime()>=Date.now()&&new Date(t.due_at!).getTime()<=Date.now()+7*86400000),[tasks]);
 const items=[...((tab==='all'||tab==='approval')?waiting.map(e=>({id:e.id,title:e.title,description:'Rascunho aguardando aprovação',date:e.occurred_at,section:'governanca'})):[]),...((tab==='all'||tab==='overdue')?overdue.map(t=>({id:t.id,title:t.title,description:'Ação vencida',date:t.due_at||'',section:'tarefas'})):[])];
 return <div className="pending-center"><div className="page-heading"><div><div className="eyebrow">CENTRAL DE PENDÊNCIAS</div><h1>O que precisa de atenção</h1><p>Aprovações e prazos organizados em um só lugar.</p></div><button className="secondary" disabled={refreshing} onClick={async()=>{setRefreshing(true);try{await onRefresh()}finally{setRefreshing(false)}}}>{refreshing?'Atualizando...':'Atualizar pendências'}</button></div><div className="stats governance-stats"><div className="stat"><span>Aprovações</span><strong>{waiting.length}</strong><small>Somente para administradores</small></div><div className="stat"><span>Vencidas</span><strong>{overdue.length}</strong><small>Ações ainda abertas</small></div><div className="stat"><span>Próximos 7 dias</span><strong>{soon.length}</strong><small>Prazos futuros</small></div></div>
 <div className="pending-tabs" role="group" aria-label="Filtrar pendências"><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>Todas</button><button className={tab==='approval'?'active':''} onClick={()=>setTab('approval')}>Aprovações</button><button className={tab==='overdue'?'active':''} onClick={()=>setTab('overdue')}>Atrasadas</button></div>
 <section className="panel list-panel">{items.map(item=><article className="audit-event" key={item.id}><strong>{item.title}</strong><p>{item.description}</p><small>{item.date?new Date(item.date).toLocaleDateString('pt-BR'):''}</small><div><button className="secondary" onClick={()=>onNavigate(item.section)}>Abrir área relacionada</button></div></article>)}{items.length===0&&<p className="muted pad">Nenhuma pendência neste filtro.</p>}</section><p className="muted hint">Indicadores calculados com os registros autorizados já carregados. Não enviamos notificações por e-mail nem executamos rotinas em segundo plano.</p></div>
}