'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
export default function ProfilePanel({userId}:{userId:string}){
const [name,setName]=useState(''),[job,setJob]=useState(''),[department,setDepartment]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
useEffect(()=>{if(!supabase)return;supabase.from('profiles').select('full_name,job_title,department').eq('user_id',userId).maybeSingle().then(({data,error})=>{if(error)setMessage(error.message);if(data){setName(data.full_name);setJob(data.job_title||'');setDepartment(data.department||'')}else{supabase?.auth.getUser().then(({data:u})=>setName(String(u.user?.user_metadata?.full_name||'')))}})},[userId]);
async function save(){if(!supabase)return;const clean=name.trim().replace(/\s+/g,' ');if(clean.split(' ').length<2||clean.length<3||clean.length>160){setMessage('Informe nome e sobrenome.');return}setBusy(true);setMessage('');const {error}=await supabase.from('profiles').upsert({user_id:userId,full_name:clean,job_title:job.trim()||null,department:department.trim()||null},{onConflict:'user_id'});setMessage(error?error.message:'Perfil atualizado.');setBusy(false)}
return <div><div className="page-heading"><div><div className="eyebrow">MINHA CONTA</div><h1>Meu perfil</h1><p>Identifique-se para que a equipe reconheça a autoria e participação nos registros.</p></div></div><section className="panel profile-form"><label>Nome completo<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="Nome e sobrenome"/></label><label>Cargo<input maxLength={120} value={job} onChange={e=>setJob(e.target.value)} placeholder="Seu cargo"/></label><label>Departamento<input maxLength={120} value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Seu departamento"/></label><button className="primary" disabled={busy} onClick={save}>Salvar perfil</button>{message&&<p role="status">{message}</p>}</section></div>
}
