'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
type Version={id:number;revision:number;title:string;body:string;status:string;changed_at:string};
export default function RecordHistory({id,workspaceId,canEdit,onSaved}:{id:string;workspaceId:string;canEdit:boolean;onSaved:()=>Promise<void>}){
const [open,setOpen]=useState(false),[versions,setVersions]=useState<Version[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{if(!open||!supabase)return;supabase.from('entry_versions').select('id,revision,title,body,status,changed_at').eq('workspace_id',workspaceId).eq('entry_id',id).order('revision',{ascending:false}).then(({data,error})=>{if(error)setError(error.message);else{const v=(data||[]) as Version[];setVersions(v);setTitle(v[0]?.title||'');setBody(v[0]?.body||'');setStatus(v[0]?.status||'')}})},[id,open,workspaceId]);
async function save(){if(!supabase)return;setBusy(true);setError('');const {error}=await supabase.rpc('update_entry_draft',{target_entry:id,new_title:title.trim(),new_body:body.trim()});if(error)setError(error.message);else{setOpen(false);await onSaved()}setBusy(false)}
return <div className="history-module"><button className="secondary" type="button" onClick={()=>setOpen(!open)}>{open?'Fechar histórico':'Histórico e edição'}</button>{open&&<div className="history-details"><h4>Versões rastreáveis</h4>{versions.map(v=><div key={v.id} className="history-item"><strong>Versão {v.revision} · {v.status}</strong><small>{new Date(v.changed_at).toLocaleString('pt-BR')}</small><p>{v.title}</p><details><summary>Conteúdo registrado</summary><p>{v.body}</p></details></div>)}{versions.length===0&&<p>Nenhuma versão encontrada.</p>}{canEdit&&status==='rascunho'&&<div className="history-form"><h4>Editar rascunho</h4><label>Título<input maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Conteúdo<textarea rows={5} maxLength={30000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="primary" disabled={busy||!title.trim()||!body.trim()} onClick={save}>Salvar nova versão</button></div>}{error&&<p className="error">{error}</p>}</div>}</div>
}