'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
import RecordExamples from './record-examples';
type Meeting={id:string;title:string;kind:string;mandatory_training?:boolean};
type Person={user_id:string;full_name:string};
export default function RitualsPanel({workspaceId,userId,canEdit,entries,people}:{workspaceId:string;userId:string;canEdit:boolean;entries:Meeting[];people:Person[]}){
 const [meeting,setMeeting]=useState(''),[agenda,setAgenda]=useState(''),[decisions,setDecisions]=useState(''),[steps,setSteps]=useState('');
 const [training,setTraining]=useState(''),[participant,setParticipant]=useState(''),[present,setPresent]=useState(true),[excused,setExcused]=useState(false),[reason,setReason]=useState(''),[mandatory,setMandatory]=useState(false);
 const [records,setRecords]=useState<{entry_id:string;participant_name:string;present:boolean;excused:boolean}[]>([]);
 const [feedbackTo,setFeedbackTo]=useState(''),[feedback,setFeedback]=useState(''),[feedbacks,setFeedbacks]=useState<{id:string;body:string;created_at:string;recipient_id:string;author_id:string}[]>([]);
 const [message,setMessage]=useState(''),[saving,setSaving]=useState(false);
 const meetings=entries.filter(e=>e.kind==='reuniao'),trainings=entries.filter(e=>e.kind==='treinamento');
 useEffect(()=>{if(!supabase||!workspaceId)return;void supabase.from('private_feedback').select('id,body,created_at,recipient_id,author_id').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(50).then(({data})=>setFeedbacks(data||[]));void supabase.from('attendance').select('entry_id,participant_name,present,excused').eq('workspace_id',workspaceId).then(({data})=>setRecords(data||[]))},[workspaceId]);
 useEffect(()=>{if(!supabase||!meeting){setAgenda('');setDecisions('');setSteps('');return;}void supabase.from('meeting_minutes').select('agenda,decisions,next_steps').eq('entry_id',meeting).maybeSingle().then(({data})=>{setAgenda(data?.agenda||'');setDecisions(data?.decisions||'');setSteps(data?.next_steps||'')})},[meeting]);
 async function saveMinutes(){if(!supabase||!meeting)return;setSaving(true);const {error}=await supabase.from('meeting_minutes').upsert({entry_id:meeting,workspace_id:workspaceId,agenda,decisions,next_steps:steps,updated_at:new Date().toISOString()},{onConflict:'entry_id'});setMessage(error?error.message:'Ata estruturada salva.');setSaving(false)}
 async function saveAttendance(){if(!supabase||!training||!participant)return;setSaving(true);const person=people.find(p=>p.user_id===participant);if(!person){setSaving(false);return;}const {error}=await supabase.from('attendance').upsert({workspace_id:workspaceId,entry_id:training,participant_user_id:participant,participant_name:person.full_name,present,excused:!present&&excused,absence_reason:!present?reason.trim()||null:null,recorded_by:userId},{onConflict:'entry_id,participant_name'});setMessage(error?error.message:'Presença ou justificativa salva.');if(!error){const r=await supabase.from('attendance').select('entry_id,participant_name,present,excused').eq('workspace_id',workspaceId);setRecords(r.data||[])}setSaving(false)}
 async function setRequired(){if(!supabase||!training)return;setSaving(true);const {error}=await supabase.rpc('set_training_required',{target_entry:training,is_required:!mandatory});setMessage(error?error.message:'Classificação do treinamento atualizada.');if(!error)setMandatory(!mandatory);setSaving(false)}
 async function sendFeedback(){if(!supabase||!feedbackTo||!feedback.trim())return;setSaving(true);const {error}=await supabase.from('private_feedback').insert({workspace_id:workspaceId,author_id:userId,recipient_id:feedbackTo,body:feedback.trim()});setMessage(error?error.message:'Feedback privado registrado.');if(!error){setFeedback('');const r=await supabase.from('private_feedback').select('id,body,created_at,recipient_id,author_id').eq('workspace_id',workspaceId).order('created_at',{ascending:false}).limit(50);setFeedbacks(r.data||[])}setSaving(false)}
 return <div><RecordExamples/><div className="page-heading"><div><div className="eyebrow">SPRINT 4</div><h1>Rituais e feedbacks</h1><p>Atas, presença, justificativas e acompanhamento individual.</p></div></div>
 <section className="panel attendance-form"><h3>Atas estruturadas</h3><select aria-label="Reunião para ata" value={meeting} onChange={e=>setMeeting(e.target.value)}><option value="">Selecione a reunião</option>{meetings.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select>{meeting&&<><p className="muted">Participantes registrados: {records.filter(r=>r.entry_id===meeting&&r.present).map(r=>r.participant_name).join(', ')||'Nenhum participante registrado'}. Novas presenças de reuniões podem ser registradas na área Reuniões.</p><label>Pauta<textarea value={agenda} readOnly={!canEdit} onChange={e=>setAgenda(e.target.value)}/></label><label>Decisões<textarea value={decisions} readOnly={!canEdit} onChange={e=>setDecisions(e.target.value)}/></label><label>Encaminhamentos<textarea value={steps} readOnly={!canEdit} onChange={e=>setSteps(e.target.value)}/></label>{canEdit&&<button className="primary" disabled={saving} onClick={()=>void saveMinutes()}>Salvar ata</button>}</>}</section>
 <section className="panel attendance-form"><h3>Treinamentos e presenças</h3><select aria-label="Treinamento" value={training} onChange={e=>{setTraining(e.target.value);setMandatory(Boolean(trainings.find(t=>t.id===e.target.value)?.mandatory_training))}}><option value="">Selecione o treinamento</option>{trainings.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select>{training&&<><p className="muted">Aderência registrada: {records.filter(r=>r.entry_id===training).length?Math.round(100*records.filter(r=>r.entry_id===training&&r.present).length/records.filter(r=>r.entry_id===training).length):0}% · Presenças: {records.filter(r=>r.entry_id===training&&r.present).length} · Faltas: {records.filter(r=>r.entry_id===training&&!r.present).length} · Justificadas: {records.filter(r=>r.entry_id===training&&!r.present&&r.excused).length}</p>{canEdit&&<><button className="secondary" onClick={()=>void setRequired()} disabled={saving}>{mandatory?'Retirar obrigatoriedade':'Marcar treinamento obrigatório'}</button><select aria-label="Colaborador" value={participant} onChange={e=>setParticipant(e.target.value)}><option value="">Selecione o colaborador</option>{people.map(p=><option value={p.user_id} key={p.user_id}>{p.full_name}</option>)}</select><label><input type="checkbox" checked={present} onChange={e=>setPresent(e.target.checked)}/> Presente</label>{!present&&<><label><input type="checkbox" checked={excused} onChange={e=>setExcused(e.target.checked)}/> Falta justificada</label><input maxLength={500} placeholder="Motivo da ausência" value={reason} onChange={e=>setReason(e.target.value)}/></>}<button className="primary" disabled={saving||!participant} onClick={()=>void saveAttendance()}>Registrar participação</button></>}</>}</section>
 <section className="panel attendance-form"><h3>Feedbacks individuais privados</h3><p className="muted">Somente autor e destinatário podem consultar cada feedback.</p>{canEdit&&<><select aria-label="Destinatário do feedback" value={feedbackTo} onChange={e=>setFeedbackTo(e.target.value)}><option value="">Selecione o destinatário</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.full_name}</option>)}</select><textarea placeholder="Feedback objetivo e construtivo" maxLength={5000} value={feedback} onChange={e=>setFeedback(e.target.value)}/><button className="primary" disabled={saving||!feedbackTo||!feedback.trim()} onClick={()=>void sendFeedback()}>Registrar feedback privado</button></>}{feedbacks.map(f=><div className="task" key={f.id}><small>{new Date(f.created_at).toLocaleDateString('pt-BR')} · {f.recipient_id===userId?'Recebido':'Enviado'}</small><span>{f.body}</span></div>)}</section>
 {message&&<p role="status">{message}</p>}</div>
}
