'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
type Member={user_id:string;role:string};type Profile={user_id:string;full_name:string};
export default function TeamPanel({workspaceId,role,userId}:{workspaceId:string;role:string;userId:string}){
 const [members,setMembers]=useState<Member[]>([]);const [profiles,setProfiles]=useState<Profile[]>([]);
 const [targetRole,setTargetRole]=useState('editor');
 const [invite,setInvite]=useState('');
 const [notice,setNotice]=useState('');
 const [busy,setBusy]=useState(false);
 async function manage(targetUser:string,newRole:string|null){if(!supabase||busy)return;if(newRole===null&&!window.confirm('Remover o acesso deste integrante à organização?'))return;setBusy(true);setNotice('');const {error}=await supabase.rpc('manage_workspace_member',{target_workspace:workspaceId,target_user:targetUser,new_role:newRole});if(error)setNotice(error.message);else{setMembers(ms=>newRole===null?ms.filter(m=>m.user_id!==targetUser):ms.map(m=>m.user_id===targetUser?{...m,role:newRole}:m));setNotice(newRole===null?'Acesso removido.':'Permissão atualizada.')}setBusy(false)}
 useEffect(()=>{if(!supabase||!workspaceId)return;supabase.from('memberships').select('user_id,role').eq('workspace_id',workspaceId).then(({data,error})=>{if(error)setNotice(error.message);else {setMembers(data||[]);supabase?.from('profiles').select('user_id,full_name').in('user_id',(data||[]).map(m=>m.user_id)).then(({data:p})=>setProfiles(p||[]))}})},[workspaceId]);
 async function create(){if(!supabase)return;setBusy(true);setNotice('');const {data,error}=await supabase.rpc('create_invite',{target_workspace:workspaceId,target_role:targetRole});if(error)setNotice(error.message);else if(data)setInvite(location.origin+'/atlas/?invite='+data);setBusy(false)}
 return <div><div className="page-heading"><div><div className="eyebrow">GOVERNANÇA</div><h1>Equipe e acessos</h1><p>Convites com expiração e controle de permissões.</p></div></div>
 <section className="panel attendance-form"><h3>Colaboradores ({members.length})</h3>{members.map(m=><div key={m.user_id} className="task"><span>{(profiles.find(p=>p.user_id===m.user_id)?.full_name||(m.user_id===userId?'Sua conta':m.user_id.slice(0,8)+'...'))}</span><small>{m.role}</small>{role==='owner'&&m.user_id!==userId&&m.role!=='owner'&&<><select aria-label={'Permissão de '+(profiles.find(p=>p.user_id===m.user_id)?.full_name||m.user_id)} value={m.role} disabled={busy} onChange={e=>void manage(m.user_id,e.target.value)}><option value="admin">Administrador</option><option value="editor">Editor</option><option value="viewer">Leitor</option></select><button className="secondary" disabled={busy} onClick={()=>void manage(m.user_id,null)}>Remover acesso</button></>}</div>)}</section>
 {['owner','admin'].includes(role)&&<section className="panel attendance-form"><h3>Criar convite</h3><p className="muted">O convite é válido por sete dias e pode ser usado uma vez. Envie apenas em canal privado.</p><div className="inline"><select value={targetRole} onChange={e=>setTargetRole(e.target.value)}><option value="admin">Administrador</option><option value="editor">Editor</option><option value="viewer">Leitor</option></select><button className="primary" disabled={busy} onClick={create}>Gerar convite</button></div>{invite&&<p><input aria-label="Link de convite" readOnly value={invite} onFocus={e=>e.currentTarget.select()} style={{width:'100%'}}/></p>}</section>}
 {notice&&<p className="error">{notice}</p>}</div>
}